## Part One

In [17]:
test_text = """
....XXMAS.
.SAMXMS...
...S..A...
..A.A.MS.X
XMASAMX.MM
X.....XA.A
S.S.S.S.SS
.A.A.A.A.A
..M.M.M.MM
.X.X.XMASX
"""

Basic algo -
* Get each row and search for XMAS or SAMX
* Get each colum and search
* Get each left-to-right diagonal
* Get each right-to-left diagonal

Let me check if numpy has easy ways of getting both the diagonals.


In [1]:
import numpy as np

In [12]:
tp = np.arange(16).reshape((4, 4))
tp

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
for offset in range(-3, 4):
    print(tp.diagonal(offset))

[12]
[ 8 13]
[ 4  9 14]
[ 0  5 10 15]
[ 1  6 11]
[2 7]
[3]


In [14]:
tp = np.rot90(tp)
for offset in range(-3, 4):
    print(tp.diagonal(offset))

[0]
[1 4]
[2 5 8]
[ 3  6  9 12]
[ 7 10 13]
[11 14]
[15]


In [15]:
import re

In [28]:
re.findall(r"XMAS|SAMX", "XMASAMX.MM")

['XMAS']

In [29]:
re.findall(r"SAMX|XMAS", "XMASAMX.MM")

['XMAS']

In [30]:
re.findall(r"XMAS|SAMX", "XMAS..SAMX.MM")

['XMAS', 'SAMX']

Ok regex will only work if the words are not overlapping. I'll just need to run two different regexes.

Now how do I convert an array of lines into a numpy array?

In [34]:
np.array(list("....XXMAS."))

array(['.', '.', '.', '.', 'X', 'X', 'M', 'A', 'S', '.'], dtype='<U1')

In [37]:
arrs = [
    np.array([1, 2, 3, 4]),
    np.array([5, 6, 7, 8]),
]
np.array(arrs)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
arrs = []
for line in test_text.splitlines():
    arrs.append(np.array(list(line.strip())))


In [41]:
arrs

[array([], dtype=float64),
 array(['.', '.', '.', '.', 'X', 'X', 'M', 'A', 'S', '.'], dtype='<U1'),
 array(['.', 'S', 'A', 'M', 'X', 'M', 'S', '.', '.', '.'], dtype='<U1'),
 array(['.', '.', '.', 'S', '.', '.', 'A', '.', '.', '.'], dtype='<U1'),
 array(['.', '.', 'A', '.', 'A', '.', 'M', 'S', '.', 'X'], dtype='<U1'),
 array(['X', 'M', 'A', 'S', 'A', 'M', 'X', '.', 'M', 'M'], dtype='<U1'),
 array(['X', '.', '.', '.', '.', '.', 'X', 'A', '.', 'A'], dtype='<U1'),
 array(['S', '.', 'S', '.', 'S', '.', 'S', '.', 'S', 'S'], dtype='<U1'),
 array(['.', 'A', '.', 'A', '.', 'A', '.', 'A', '.', 'A'], dtype='<U1'),
 array(['.', '.', 'M', '.', 'M', '.', 'M', '.', 'M', 'M'], dtype='<U1'),
 array(['.', 'X', '.', 'X', '.', 'X', 'M', 'A', 'S', 'X'], dtype='<U1')]

In [43]:
test_input = np.array(arrs[1:])
test_input

array([['.', '.', '.', '.', 'X', 'X', 'M', 'A', 'S', '.'],
       ['.', 'S', 'A', 'M', 'X', 'M', 'S', '.', '.', '.'],
       ['.', '.', '.', 'S', '.', '.', 'A', '.', '.', '.'],
       ['.', '.', 'A', '.', 'A', '.', 'M', 'S', '.', 'X'],
       ['X', 'M', 'A', 'S', 'A', 'M', 'X', '.', 'M', 'M'],
       ['X', '.', '.', '.', '.', '.', 'X', 'A', '.', 'A'],
       ['S', '.', 'S', '.', 'S', '.', 'S', '.', 'S', 'S'],
       ['.', 'A', '.', 'A', '.', 'A', '.', 'A', '.', 'A'],
       ['.', '.', 'M', '.', 'M', '.', 'M', '.', 'M', 'M'],
       ['.', 'X', '.', 'X', '.', 'X', 'M', 'A', 'S', 'X']], dtype='<U1')

In [52]:
xmas = re.compile(r"XMAS")
samx = re.compile(r"SAMX")


def count_xmas(line: str) -> int:
    return len(xmas.findall(line)) + len(samx.findall(line))

In [53]:
count_xmas("XMASAMX.MM")

2

In [55]:
total_count = 0
n = test_input.shape[0]

for row in test_input:
    line = "".join(row)
    total_count += count_xmas(line)

for col in test_input.T:
    line = "".join(col)
    total_count += count_xmas(line)

# left-to-right diagonals
for offset in range(-(n - 1), n):
    items = test_input.diagonal(offset)
    line = "".join(items)
    total_count += count_xmas(line)

# right-to-left diagonals
test_input = np.rot90(test_input)
for offset in range(-(n - 1), n):
    items = test_input.diagonal(offset)
    line = "".join(items)
    total_count += count_xmas(line)


In [56]:
total_count

18

In [68]:
%reset

In [69]:
import numpy as np
import re

In [70]:
def to_array(filename):
    arrs = []
    with open(filename) as f:
        for line in f:
            arrs.append(np.array(list(line.strip())))
    return np.array(arrs)

In [71]:
matrix = to_array("input.txt")
matrix.shape

(140, 140)

In [75]:
xmas = re.compile(r"XMAS")
samx = re.compile(r"SAMX")


def count_xmas(line: str) -> int:
    return len(xmas.findall(line)) + len(samx.findall(line))


def search_xmas(matrix):
    total_count = 0
    n = matrix.shape[0]

    for row in matrix:
        line = "".join(row)
        total_count += count_xmas(line)

    for col in matrix.T:
        line = "".join(col)
        total_count += count_xmas(line)

    # left-to-right diagonals
    for offset in range(-(n - 1), n):
        items = matrix.diagonal(offset)
        line = "".join(items)
        total_count += count_xmas(line)

    # right-to-left diagonals
    matrix = np.rot90(matrix)
    for offset in range(-(n - 1), n):
        items = matrix.diagonal(offset)
        line = "".join(items)
        total_count += count_xmas(line)

    return total_count

In [76]:
search_xmas(matrix)

2554

## Part Two

In [83]:
test_text = """
.M.S......
..A..MSMS.
.M.S.MAA..
..A.ASMSM.
.M.S.M....
..........
S.S.S.S.S.
.A.A.A.A..
M.M.M.M.M.
..........
"""

Basic Algo -
* Scan each row for either an 'S' or an 'M', and get an X from the matrix from that point on.
* I need only look for left-to-right, go forward 2 steps, and then right-to-left. I don't need reverse-X where I am going right-to-left, going back 2 steps and then going left-to-right, because it was already covered.
* I get the two arms of X as two strings, check if both of them are either SAM or MAS.

In [103]:
def get_x(matrix: np.ndarray, start: tuple[int, int]) -> tuple[str, str]:
    row, col = start
    n = matrix.shape[0]
    if row + 2 >= n or col + 2 >= n:
        return "", ""

    left_to_right = [
        matrix[row][col],
        matrix[row + 1, col + 1],
        matrix[row + 2, col + 2]
    ]
    col = col + 2
    right_to_left = [
        matrix[row, col],
        matrix[row + 1, col - 1],
        matrix[row + 2, col - 2]
    ]
    return "".join(left_to_right), "".join(right_to_left)


In [104]:
arrs = []
for line in test_text.splitlines():
    arrs.append(np.array(list(line.strip())))

test_input = np.array(arrs[1:])
test_input

array([['.', 'M', '.', 'S', '.', '.', '.', '.', '.', '.'],
       ['.', '.', 'A', '.', '.', 'M', 'S', 'M', 'S', '.'],
       ['.', 'M', '.', 'S', '.', 'M', 'A', 'A', '.', '.'],
       ['.', '.', 'A', '.', 'A', 'S', 'M', 'S', 'M', '.'],
       ['.', 'M', '.', 'S', '.', 'M', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['S', '.', 'S', '.', 'S', '.', 'S', '.', 'S', '.'],
       ['.', 'A', '.', 'A', '.', 'A', '.', 'A', '.', '.'],
       ['M', '.', 'M', '.', 'M', '.', 'M', '.', 'M', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.']], dtype='<U1')

In [105]:
n = test_input.shape[0]
count_x_mas = 0
for row in range(n):
    for col in range(n):
        if test_input[row, col] == 'M' or test_input[row, col] == 'S':
            left_to_right, right_to_left = get_x(test_input, (row, col))
            if (left_to_right == "MAS" or left_to_right == "SAM") and (
                    right_to_left == "MAS" or right_to_left == "SAM"):
                count_x_mas += 1

In [106]:
count_x_mas

9

In [91]:
test_input[0, 0]

np.str_('.')

In [107]:
matrix = to_array("input.txt")

In [115]:
def search_x_mas(matrix):
    n = matrix.shape[0]
    count_x_mas = 0
    for row in range(n):
        for col in range(n):
            if matrix[row, col] == 'M' or matrix[row, col] == 'S':
                left_to_right, right_to_left = get_x(matrix, (row, col))
                if (left_to_right == "MAS" or left_to_right == "SAM") and (
                        right_to_left == "MAS" or right_to_left == "SAM"):
                    count_x_mas += 1
    return count_x_mas

In [116]:
search_x_mas(matrix)

1916