In [1]:
import numpy as np

$$
\displaylines{
94a + 22b = 8400 \\
34a + 67b = 5400
}
$$

$$
M = \begin{bmatrix}
94 & 22 \\
34 & 67
\end{bmatrix}
$$

$$
v = \begin{bmatrix}
a \\
b
\end{bmatrix}
$$

$$
p = \begin{bmatrix}
8400 \\
5400
\end{bmatrix}
$$

$$
Mv = p
$$

In [28]:
m = np.array([[94, 22],
              [34, 67]])
p = np.array([8400, 5400])
v = np.linalg.solve(m, p)
print(m @ v)
v

[8400. 5400.]


array([80., 40.])

In [29]:
m = np.array([[26, 67],
              [66, 21]])
p = np.array([12748, 12176])
v = np.linalg.solve(m, p)
print(m @ v)
print(v)

[12748. 12176.]
[141.40454076 135.39525284]


In [30]:
m = np.array([[17, 84],
              [86, 37]])
p = np.array([7870, 6450])
v = np.linalg.solve(m, p)
print(m @ v)
v

[7870. 6450.]


array([38., 86.])

In [33]:
m = np.array([[69, 27],
              [23, 71]])
p = np.array([18641, 10279])
v = np.linalg.solve(m, p)
print(m @ v)
print(np.linalg.det(m))
v

[18641. 10279.]
4278.000000000002


array([244.50163628,  65.56989247])

In [35]:
from collections import namedtuple

In [36]:
Solution = namedtuple("Solution", ["button_a", "button_b", "prize"])

Maximize $N$ and minimize $J$ subject to these constraints -
$$
\displaylines{
J = \sum_{i=1}^N 3a_i + b_i \\
\sum_{i=1}^N a_i <= 100 \\
\sum_{i=1}^N b_i <= 100 \\
}
$$

All $a_i$ and $b_i$ are known. The only unknown is $N$ and therefore $J$.

$$
\begin{align}
J &= 3 \sum_{i=1}^N a_i + \sum_{i=1}^N + b_i \\
&<= 3 \times 100 + 100 \\
&<= 400
\end{align}
$$

In [37]:
test_input = """
Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=8400, Y=5400

Button A: X+26, Y+66
Button B: X+67, Y+21
Prize: X=12748, Y=12176

Button A: X+17, Y+86
Button B: X+84, Y+37
Prize: X=7870, Y=6450

Button A: X+69, Y+23
Button B: X+27, Y+71
Prize: X=18641, Y=10279
"""

In [ ]:
Prize = namedtuple("Prize", 